# Generated by Django 5.1.15 on 2026-09-21 04:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=32)),
                ('status', models.CharField(choices=[('TRIGGERED', 'Triggered'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='TRIGGERED', max_length=32)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='services.service')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('INCIDENT_TRIGGERED', 'Incident Triggered'), ('ALERT_ATTACHED', 'Alert Attached'), ('INCIDENT_ACKNOWLEDGED', 'Incident Acknowledged'), ('INCIDENT_RESOLVED', 'Incident Resolved'), ('INCIDENT_REOPENED', 'Incident Reopened')], max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_events', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Incident Event',
                'verbose_name_plural': 'Incident Events',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['service', 'fingerprint'], name='incidents_i_service_48aefa_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='incidents_i_status_9a4f12_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['triggered_at'], name='incidents_i_trigger_a7c382_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['resolved_at'], name='incidents_i_resolve_9d0fd6_idx'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('service', 'fingerprint'), name='unique_active_incident_service_fingerprint'),
        ),
        migrations.AddIndex(
            model_name='incidentevent',
            index=models.Index(fields=['incident', 'created_at'], name='incidents_i_inciden_a6ec40_idx'),
        ),
    ]
