# Generated by Django 5.1.15 on 2026-09-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentevent',
            name='event_type',
            field=models.CharField(choices=[('INCIDENT_TRIGGERED', 'Incident Triggered'), ('ALERT_ATTACHED', 'Alert Attached'), ('RESPONDER_ASSIGNED', 'Responder Assigned'), ('ROUTING_UNAVAILABLE', 'Routing Unavailable'), ('INCIDENT_ACKNOWLEDGED', 'Incident Acknowledged'), ('INCIDENT_RESOLVED', 'Incident Resolved'), ('INCIDENT_REOPENED', 'Incident Reopened')], max_length=64),
        ),
    ]
