# Generated by Django 5.1.15 on 2026-09-21 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalation', '0001_initial'),
        ('incidents', '0002_alter_incidentevent_event_type'),
        ('services', '0002_service_escalation_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='automation_generation',
            field=models.PositiveIntegerField(default=1, help_text='Lifecycle version incremented on reopen to invalidate stale asynchronous automation tasks.'),
        ),
        migrations.AddField(
            model_name='incident',
            name='current_escalation_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='escalation.escalationlevel'),
        ),
        migrations.AlterField(
            model_name='incidentevent',
            name='event_type',
            field=models.CharField(choices=[('INCIDENT_TRIGGERED', 'Incident Triggered'), ('ALERT_ATTACHED', 'Alert Attached'), ('RESPONDER_ASSIGNED', 'Responder Assigned'), ('ROUTING_UNAVAILABLE', 'Routing Unavailable'), ('INCIDENT_ACKNOWLEDGED', 'Incident Acknowledged'), ('INCIDENT_RESOLVED', 'Incident Resolved'), ('INCIDENT_REOPENED', 'Incident Reopened'), ('ESCALATION_STARTED', 'Escalation Started'), ('INCIDENT_ESCALATED', 'Incident Escalated'), ('ESCALATION_EXHAUSTED', 'Escalation Exhausted'), ('ESCALATION_TARGET_UNAVAILABLE', 'Escalation Target Unavailable')], max_length=64),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['current_escalation_level'], name='incidents_i_current_c7e069_idx'),
        ),
    ]
