# Generated by Django 5.1.15 on 2026-09-21 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalation_policies', to='users.team')),
            ],
            options={
                'verbose_name': 'Escalation Policy',
                'verbose_name_plural': 'Escalation Policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EscalationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='1-based sequence order within the escalation policy.')),
                ('target_type', models.CharField(choices=[('CURRENT_ON_CALL', 'Current On-Call'), ('USER', 'User')], default='CURRENT_ON_CALL', max_length=32)),
                ('wait_minutes', models.PositiveIntegerField(default=15, help_text='Minutes to wait after notifying this level before escalating to the next.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_user', models.ForeignKey(blank=True, help_text='Target user when target_type is USER.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalation_levels', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='escalation.escalationpolicy')),
            ],
            options={
                'verbose_name': 'Escalation Level',
                'verbose_name_plural': 'Escalation Levels',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('policy', 'order'), name='unique_policy_level_order')],
            },
        ),
    ]
