# Generated by Django 5.1.15 on 2026-09-21 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='users.team')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_override', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='scheduling.schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_rotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schedule Rotation',
                'verbose_name_plural': 'Schedule Rotations',
                'ordering': ['start_time', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('team',), name='unique_active_primary_schedule_per_team'),
        ),
        migrations.AddIndex(
            model_name='schedulerotation',
            index=models.Index(fields=['schedule', 'start_time', 'end_time'], name='scheduling__schedul_fdd491_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerotation',
            index=models.Index(fields=['schedule', 'is_override'], name='scheduling__schedul_2bb6fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='schedulerotation',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='rotation_end_time_after_start_time'),
        ),
    ]
